import { ArrowUpRight, CalendarDays, ChevronRight, Clock3, Users, UserRoundPlus, WalletCards } from "lucide-react";
import { useAuthStore } from "../../application/stores/authStore";
import ClinicalDashboardPage from "./ClinicalDashboardPage";

const metrics = [
  { label: "Patients today", value: "248", change: "+8.2%", icon: Users, color: "bg-teal-50 text-teal-700" },
  { label: "Appointments", value: "128", change: "+12.0%", icon: CalendarDays, color: "bg-blue-50 text-blue-700" },
  { label: "New admissions", value: "36", change: "+5.4%", icon: UserRoundPlus, color: "bg-violet-50 text-violet-700" },
  { label: "Collection", value: "$18.4k", change: "+3.1%", icon: WalletCards, color: "bg-amber-50 text-amber-700" },
];
const appointments = [["10:00 AM", "Alicia Reyes", "Dr. Maria Santos", "Cardiology", "AR"], ["10:30 AM", "Jonathan Cruz", "Dr. Nathan Lim", "General practice", "JC"], ["11:00 AM", "Sofia Navarro", "Dr. Maria Santos", "Cardiology", "SN"], ["11:15 AM", "Ethan Tan", "Dr. Patricia Wong", "Pediatrics", "ET"]];

export default function DashboardPage() {
  const user = useAuthStore((state) => state.user);
  const role = user?.role ?? (user?.role_id === 2 ? "doctor" : user?.role_id === 3 ? "nurse" : "administrator");
  if (role === "doctor" || role === "nurse") return <ClinicalDashboardPage role={role} />;
  return <div className="mx-auto max-w-7xl space-y-7"><section className="flex flex-col justify-between gap-4 rounded-2xl bg-slate-900 px-6 py-6 text-white sm:flex-row sm:items-center"><div><p className="text-sm font-medium text-teal-300">Good morning, Avery</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Here’s what needs your attention.</h2></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-400 px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-teal-300">View schedule <ChevronRight size={17} /></button></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, change, icon: Icon, color }) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className={`grid h-11 w-11 place-items-center rounded-xl ${color}`}><Icon size={20} /></div><span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700"><ArrowUpRight size={12} />{change}</span></div><p className="mt-5 text-sm font-medium text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold tracking-tight text-slate-900">{value}</p></article>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.55fr_1fr]"><article className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h3 className="font-bold text-slate-900">Today’s appointments</h3><p className="mt-1 text-sm text-slate-500">Monday, 4 August</p></div><button className="text-sm font-bold text-teal-700 hover:text-teal-800">View all</button></div><div className="divide-y divide-slate-100">{appointments.map(([time, name, doctor, unit, initials]) => <div key={name} className="flex items-center gap-3 px-6 py-4"><div className="w-16 text-sm font-bold text-slate-700">{time}</div><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-600">{initials}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-800">{name}</p><p className="truncate text-xs text-slate-500">{doctor}</p></div><span className="hidden rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600 sm:block">{unit}</span></div>)}</div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Department load</h3><p className="mt-1 text-sm text-slate-500">Patients checked in</p></div><button className="text-sm font-bold text-teal-700">Details</button></div><div className="mt-7 space-y-5">{[["General practice", 78, "bg-teal-500"], ["Cardiology", 62, "bg-blue-500"], ["Pediatrics", 55, "bg-violet-500"], ["Orthopedics", 38, "bg-amber-500"]].map(([name, value, color]) => <div key={name as string}><div className="mb-2 flex justify-between text-sm"><span className="font-medium text-slate-700">{name as string}</span><span className="font-bold text-slate-900">{value as number}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color as string}`} style={{ width: `${value}%` }} /></div></div>)}</div><div className="mt-7 rounded-xl bg-slate-50 p-4"><div className="flex gap-3"><Clock3 size={19} className="mt-0.5 text-teal-700" /><div><p className="text-sm font-bold text-slate-800">Shift handover at 2:00 PM</p><p className="mt-1 text-xs leading-5 text-slate-500">Review new admissions and priority cases before the afternoon round.</p></div></div></div></article></section></div>;
}
