import { ArrowRight, CheckCircle2, HeartPulse, ShieldCheck, Stethoscope } from "lucide-react";
import { Link } from "react-router-dom";
import Logo from "../components/Logo";

export default function LandingPage() {
  return <div className="min-h-screen bg-slate-950 text-white"><header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Logo /><Link to="/login" className="rounded-xl border border-slate-700 px-5 py-2.5 text-sm font-semibold transition hover:border-teal-300 hover:text-teal-300">Staff sign in</Link></header>
    <main><section className="relative mx-auto grid max-w-7xl gap-14 overflow-hidden px-6 pb-24 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pb-32"><div className="absolute -left-40 top-0 h-96 w-96 rounded-full bg-teal-500/10 blur-3xl" /><div className="relative"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-teal-400/20 bg-teal-400/10 px-3 py-1.5 text-sm font-medium text-teal-300"><span className="h-2 w-2 rounded-full bg-teal-300" />Hospital operations, in one place</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.04] tracking-tight sm:text-6xl">Clearer care.<br /><span className="text-teal-300">Better outcomes.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">SegHIS gives care teams a single, calm workspace for patients, appointments, departments, and medical records.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/login" className="inline-flex items-center gap-2 rounded-xl bg-teal-400 px-5 py-3.5 font-bold text-slate-950 transition hover:bg-teal-300">Open workspace <ArrowRight size={18} /></Link><a href="#capabilities" className="rounded-xl px-5 py-3.5 font-semibold text-slate-300 transition hover:text-white">Explore capabilities</a></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-400"><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-teal-300" />Role-based access</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-teal-300" />Secure patient data</span></div></div><div className="relative rounded-3xl border border-white/10 bg-slate-900/70 p-5 shadow-2xl shadow-black/30 backdrop-blur sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-400">Today at a glance</p><p className="mt-1 text-2xl font-bold">Care operations</p></div><div className="grid h-11 w-11 place-items-center rounded-xl bg-teal-400 text-slate-950"><HeartPulse /></div></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-800 p-4"><p className="text-sm text-slate-400">Appointments</p><p className="mt-2 text-3xl font-bold">128</p><p className="mt-1 text-xs text-teal-300">+12% from Monday</p></div><div className="rounded-2xl bg-slate-800 p-4"><p className="text-sm text-slate-400">Available beds</p><p className="mt-2 text-3xl font-bold">42</p><p className="mt-1 text-xs text-teal-300">Across 8 wards</p></div></div><div className="mt-4 rounded-2xl border border-slate-800 p-4"><p className="text-sm font-semibold">Next appointment</p><div className="mt-3 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-rose-400/15 text-rose-300"><Stethoscope size={19} /></div><div><p className="text-sm font-semibold">Cardiology consultation</p><p className="text-xs text-slate-400">Dr. Maria Santos · 10:30 AM</p></div></div></div></div></section>
    <section id="capabilities" className="bg-white px-6 py-20 text-slate-900"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-teal-700">Designed for care teams</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">Everything essential, without the clutter.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Patient-first records", "Keep a complete view of each patient's journey.", HeartPulse], ["Coordinated workflow", "Bring appointments, departments, and teams together.", Stethoscope], ["Safe by design", "Role-based access keeps sensitive data protected.", ShieldCheck]].map(([title, copy, Icon]) => { const CardIcon = Icon as typeof HeartPulse; return <article key={title as string} className="rounded-2xl border border-slate-200 p-6"><div className="grid h-11 w-11 place-items-center rounded-xl bg-teal-50 text-teal-700"><CardIcon /></div><h3 className="mt-5 text-lg font-bold">{title as string}</h3><p className="mt-2 leading-7 text-slate-600">{copy as string}</p></article>; })}</div></div></section></main></div>;
}
