import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, ChevronDown, Menu, Search, Settings } from "lucide-react";
import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { getNotifications, markNotificationsRead } from "../../api/notificationsApi";
import { useAuthStore } from "../../application/stores/authStore";

const titles: Record<string, string> = { "/dashboard": "Overview", "/patients": "Patients", "/appointments": "Appointments", "/departments": "Departments", "/doctors": "Doctors", "/nurses": "Nurses", "/notifications": "Notifications", "/settings": "Settings" };
export default function Topbar() {
  const [notificationsOpen, setNotificationsOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const navigate = useNavigate(); const client = useQueryClient(); const user = useAuthStore((state) => state.user); const title = titles[useLocation().pathname] ?? "SegHIS";
  const { data: notifications = [] } = useQuery({ queryKey: ["notifications"], queryFn: getNotifications }); const unread = notifications.filter((item) => !item.is_read).length;
  const openNotifications = async () => { setNotificationsOpen((open) => !open); setProfileOpen(false); if (unread) { await markNotificationsRead(); client.invalidateQueries({ queryKey: ["notifications"] }); } };
  return <header className="relative flex h-20 shrink-0 items-center justify-between border-b border-slate-200 bg-white px-5 sm:px-8"><div className="flex items-center gap-3"><button className="lg:hidden"><Menu size={23} /></button><div><h1 className="text-xl font-bold tracking-tight text-slate-900">{title}</h1><p className="hidden text-sm text-slate-500 sm:block">Monday, 4 August 2026</p></div></div><div className="flex items-center gap-3"><div className="relative hidden md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input className="w-56 rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-teal-500" placeholder="Search records" /></div><div className="relative"><button onClick={openNotifications} aria-label="Notifications" className="relative grid h-10 w-10 place-items-center rounded-xl hover:bg-slate-100"><Bell size={20} />{unread > 0 && <span className="absolute -right-1 -top-1 min-w-5 rounded-full bg-rose-500 px-1 text-[10px] font-bold leading-5 text-white">{unread > 99 ? "99+" : unread}</span>}</button>{notificationsOpen && <div className="absolute right-0 top-12 z-50 w-80 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl"><div className="border-b px-4 py-3"><p className="font-bold">Notifications</p></div>{notifications.slice(0, 3).map((item) => <div key={item.id} className="border-b border-slate-100 px-4 py-3"><p className="text-sm font-bold text-slate-800">{item.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.message}</p></div>)}{notifications.length === 0 && <p className="p-4 text-sm text-slate-500">You’re all caught up.</p>}<Link onClick={() => setNotificationsOpen(false)} to="/notifications" className="block bg-slate-50 px-4 py-3 text-center text-sm font-bold text-teal-700 hover:bg-teal-50">See all notifications</Link></div>}</div><div className="relative"><button onClick={() => { setProfileOpen((open) => !open); setNotificationsOpen(false); }} className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-slate-100"><div className="grid h-9 w-9 place-items-center rounded-full bg-slate-900 text-sm font-bold text-teal-300">{user?.name?.slice(0, 2).toUpperCase() ?? "AM"}</div><ChevronDown size={15} className="hidden sm:block" /></button>{profileOpen && <div className="absolute right-0 top-12 z-50 w-52 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><div className="border-b px-3 py-2"><p className="text-sm font-bold">{user?.name ?? "Account"}</p><p className="text-xs text-slate-500">{user?.username}</p></div><button onClick={() => { navigate("/settings"); setProfileOpen(false); }} className="mt-1 flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-sm font-medium hover:bg-slate-100"><Settings size={17} />Settings</button></div>}</div></div></header>;
}
